version: '2'
services:
  eddy-automl:
    build: .
    image: eddy-automl:latest
    depends_on: 
      - broker
    ports:
      - 8888:8888
    environment: 
      - JUPYTER_ENABLE_LAB=yes
  
  # Kafka Cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,HOST://localhost:9092